name: Upload install scripts
on:
  push:


jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Test install.sh on Linux
      shell: bash
      run: |
        cat install.sh | bash
        ~/.duckdb/cli/latest/duckdb -c "select 42"

  test-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v6
  
    - name: Test install.ps1 on Windows
      shell: pwsh
      run: |
        ./install.ps1
        $sh = New-Object -ComObject WScript.Shell
        $target = $sh.CreateShortcut("$Home\Desktop\DuckDB.lnk").TargetPath
        & $target -c "select 42"

  upload:
    needs: [test-linux, test-windows]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install
        shell: bash
        run: pip install awscli

      - name: Upload
        env:
          DUCKDB_INSTALL_S3_ENDPOINT: ${{ secrets.DUCKDB_INSTALL_S3_ENDPOINT }}
          DUCKDB_INSTALL_S3_ID: ${{ secrets.DUCKDB_INSTALL_S3_ID }}
          DUCKDB_INSTALL_S3_SECRET: ${{ secrets.DUCKDB_INSTALL_S3_SECRET }}

        shell: bash
        run: |
          aws s3 cp --dryrun install.sh s3://duckdb-install/
          aws s3 cp --dryrun install.ps1 s3://duckdb-install/
