name: Upload install scripts
on:
  push:

env:
  GH_TOKEN: ${{ secrets.DUCKDBLABS_BOT_TOKEN }}

jobs:
  test-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Test install.sh on Linux
      shell: bash
      run: |
        cat install.sh | bash
        ~/.duckdb/cli/latest/duckdb -c "select 42"

  test-osx:
    runs-on: osx-latest
    steps:
    - name: Test install.sh on OSX
      shell: bash
      run: |
        cat install.sh | bash
        ~/.duckdb/cli/latest/duckdb -c "select 42"

  test-windows:
    runs-on: windows-latest
    steps:
    - name: Test install.ps1 on OSX
      shell: bash
      run: |
        powershell -noexit "& ""install.ps1"""

  upload:
    needs: [test-linux, test-osx, test-windows]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Upload
        shell: bash
        run: |
          echo 'hello upload'
